FROM node:20.15.0-alpine3.20
 
EXPOSE 8080
ENV DB_HOST=mysql
RUN useradd expense
RUN expense:expense -R /opt/server
WORKDIR /opt/server
COPY package.json .
COPY *.js /opt/server/
RUN npm install
USER expense
CMD [ "node","index.js" ]


# addgroup -S expense && adduser -S expense -G expense \